--- Documentation par Oco'Dev
--- https://ocodev-lib.gitbook.io/ocodev-lib
--- Discord Oco'Dev
--- https://discord.gg/ocodev
--- Generated by EmmyLua(https://github.com/EmmyLua)


Keys = {}
Keys.Register = function(Controls, ControlName, Description, Action)
    local _Keys = {
        CONTROLS = Controls
    }
    RegisterKeyMapping(string.format('rageui-%s', ControlName), Description, "keyboard", Controls)
    RegisterCommand(string.format('rageui-%s', ControlName), function(source, args)
        if (Action ~= nil) then
            Action();
        end
    end, false)
    return setmetatable(_Keys, Keys)
end

function Keys:Exists(Controls)
    return self.CONTROLS == Controls and true or false
end
